# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22.3"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test #this one reference script bash to "dev/golang/scripts/unit-testing.sh"
      # this add your enviroment
      # env:
      #   STORAGE_EMULATOR_HOST: "localhost:9000"
      #   GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}